### ISSUE TITLE
Results from GRF-resW

### ISSUE THREAD

**Issue by gannawag** [Microsoft/EconML#1]
Hello, 

I am working through the ORF paper (arXiv:1806.03467v2 [cs.LG] 12 Jul 2018) and I have a small question that I couldn't figure out on my own.

What are the results from the simulation when Y and T are residualized on W only and not on x? Is there a reason these aren't included in the paper but are in the R code GRF_treatment_effects.R?

Here is the snippet from the paper:

> (3) GRF-Res: We perform a naive combination of double ML and GRF by first residualizing the treatments and outcomes on the both the features x and controls W , then running GRF R package on the residualized treatments Tˆ , residualized outcomes Yˆ , and features x. 

and from the R code: 
`### Comparison #3`
` # Residualize on W, fit on x`
`forest <- causal_forest(input, data$res_Y_W, data$res_T_W)`
`tau_hat <- predict(forest, test_data)`
`results3[te_col] <- tau_hat$predictions`

Thanks!

**Comment by moprescu** [comment]
Hi Grant,

We decided to exclude this scenario (`# Residualize on W, fit on x`) from the paper because it was performing similarly (same bias distribution, higher variance) to when we residualized on x U W. I included some very early figures that show this: 

![image](https://user-images.githubusercontent.com/14111979/52091513-aa9e7b80-2582-11e9-9e81-10bd480a9fa7.png)

![image](https://user-images.githubusercontent.com/14111979/52091892-edad1e80-2583-11e9-9092-aeee4304f27b.png)

I hope this helps!

**Comment by gannawag** [comment]
Got it. That makes a ton of sense. Thanks!

- Grant Gannaway
208 881-7878
