### ISSUE TITLE
Determining price elasticity of demand with DeepIVEstimator

### ISSUE THREAD

**Issue by rmitsch** [microsoft/EconML#194]
I would like to compute the price elasticity of demand for my dataset using the `DeepIVEstimator`. I can find examples on how to do that in the tutorials for [double machine learning](https://render.githubusercontent.com/view/ipynb?commit=481712e00f444229b9151a83793a13e355a6e55f&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d6963726f736f66742f45636f6e4d4c2f343831373132653030663434343232396239313531613833373933613133653335356136653535662f6e6f7465626f6f6b732f446f75626c652532304d616368696e652532304c6561726e696e672532304578616d706c65732e6970796e62&nwo=microsoft%2FEconML&path=notebooks%2FDouble+Machine+Learning+Examples.ipynb&repository_id=131646318&repository_type=Repository#4.-Example-Usage-with-Single-Continuous-Treatment-Observational-Data) and for the [`OrthogonalRandomForest`](https://render.githubusercontent.com/view/ipynb?commit=481712e00f444229b9151a83793a13e355a6e55f&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d6963726f736f66742f45636f6e4d4c2f343831373132653030663434343232396239313531613833373933613133653335356136653535662f6e6f7465626f6f6b732f4f7274686f676f6e616c25323052616e646f6d253230466f726573742532304578616d706c65732e6970796e62&nwo=microsoft%2FEconML&path=notebooks%2FOrthogonal+Random+Forest+Examples.ipynb&repository_id=131646318&repository_type=Repository#4.-Example-usage-with-real-continuous-treatment-observational-data), but none in the tutorial for the [`DeepIVEstimator`](https://github.com/microsoft/EconML/blob/master/notebooks/Deep%20IV%20Examples.ipynb).
Since the interfaces differ slightly, I'm not sure how to achieve this with `DeepIVEstimator` (e. g. it doesn't implement `const_marginal_effect()`). I guess I could 
* fit the model assuming my price as `T`, my demand as `Y`, my covariates/features as `X`, my instrumental variable as `Z`,
* infer the result for manipulated (lower/higher than in the original dataset) values of `T`,
* examine the inferred results for these varying treatment values to conclude their effect on `Y` (i. e. how the demand is expected to behave w.r.t. changing prices).

My question here is: Is there a more direct way to do this? Like e. g. `LinearDMLCateEstimator.const_marginal_effect_interval()` seems to enable it in the respective tutorial. Maybe I'm missing something obvious. 

Thanks for this great tool!

**Comment by kbattocchi** [comment]
Thanks for your interest.  Deep IV estimates a more general type of model than our other estimators - the marginal effect is not assumed to be constant.  If you have just a single product (so that T is a vector of (log-)prices and Y is the vector of (log-)sales), and you want the marginal effect at some particular price, you can use `marginal_effect(T, X)`.  Alternatively, you can call `predict(T, X)` to predict the actual sales given a particular price level and features, or `effect(X, T0, T1)` to get the change in sales from moving from price T0 to T1 (but note the difference in the order of the arguments).

However, note that the flexibility of Deep IV comes at a price: in order for the effect to be completely identified, there are very strong conditions on the data generating process which might not be satisfied in practice (e.g. if the distribution of prices conditional on X and Z is symmetric for every Z, Deep IV cannot distinguish between the true Y(X, T) and Y(X, T) + T).  Also note that the only form of inference that we support with Deep IV is bootstrapping, which would require retraining your neural networks many times over different subsampled copies of your data (which could take a long time).

If you have an instrument and are willing to make the assumption that the marginal treatment effect is constant, then we have a prototype of a different technique called DML IV, described in [this paper](https://arxiv.org/pdf/1905.10176.pdf) that might work.  We're hoping to get an implementation into a public release before the end of the year, but in the meantime you can check out the prototypes folder of this repository to see a rough cut.

Hope that helps,
Keith

**Comment by rmitsch** [comment]
It does help. Thanks for the extensive answer!
