### ISSUE TITLE
Bootstrap named args

### ISSUE THREAD

**Issue by vsyrgkanis** [microsoft/EconML#294]
One question: if a fit argument is not a numpy array that needs to be split (e.g. inference). Then wouldn't this line replace it with a None?

https://github.com/microsoft/EconML/blob/80264390106a8c57e2286177a2c4f8a47b51a32e/econml/bootstrap.py#L76

Is that the desired behavior?

**Comment by kbattocchi** [comment]
At the moment, all arguments (named or positional) must either be arrays or None; `convertArg` takes the appropriate subset of the argument if it's not None or just passes None through untouched.  In the case of `inference`, this doesn't cause problems because that argument is stripped out by the logic in the base cate estimator before `fit` is called on the bootstrap estimator.  However, once we start supporting other fit arguments (e.g. a flag to decide whether to cache nuisances) the `convertArg` logic needs to change to do something slightly smarter.  Unfortunately I think there will always be some amount of guesswork because we want this wrapper to support wrapping things where we don't know the signature of fit in advance, so we don't know what the different arguments really mean and how they should be treated.

**Comment by vasilismsr** [comment]
The only thing I was wondering we could do would be:
1) Check if the argument is a numpy array and check if the first dimension is of the same size as n
2) If that is the case then do the subset. Otherwise pass the whole argument as is.

I think this might cover most uses of other fit arguments which typically are not numpy arrays but some hyperparams and if they are numpy arrays they are not of the size of the input data samples. 

Maybe we could also add some docstring that this is the behavior for maintenance purposes.
