### ISSUE TITLE
Fail to use inference in DMLCateEstimator

### ISSUE THREAD

**Issue by ncorream** [microsoft/EconML#296]
First of all, thank you for your work in ML causality! I have learned a lot thanks to this package and using it would help me a lot with my studies. 

Now, to my problem, I am trying to use a DMLCateEstimator with a continuous treatment and a continuous outcome. My income data is formatted as a pandas dataframe. When I pass the code of to fit the estimator with the bootstrap inference like this:

est = DMLCateEstimator(model_y=GradientBoostingRegressor(),
                       model_t=GradientBoostingRegressor(),
                       model_final=LassoCV())
est.fit(y, T, X=W, W=W, inference="bootstrap") 

I get the following error:

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

But if I forgo the inference it works just fine. The only problem is that I would need to use the inference, so I am stuck right now. 

Thanks in advance!

**Comment by vsyrgkanis** [comment]
I believe this might be a problem that you are passing pandas data frames to the package instead of numpy arrays. Currently our package only supports consistently numpy arrays. Could you try changing the call to:
est.fit(y.values, T.values, X=W.values, W=None, inference="bootstrap")

Also the api, has the following contract: we are controlling for any effect modifier. So if you set X=W, then you should set W=None, since you don't want to control for any more variables other than the X. If you specify X=W and W=W, then internally there might be feature duplication, as we will try to control for both X and W.

**Comment by ncorream** [comment]
Worked like a charm! Thank you very much!

Also thanks also about the tip to put W=None. My intention was to specify a set of confounders, and then be able to do CATE for a specific values of those confounders. I am still learning causal inference, so I could have been confusing some terms. 

Thank you again!

**Comment by vsyrgkanis** [comment]
No worries! Our API went with this approach, as it's more robust to always control for the things that you want to use as effect modifiers. So we are always "controlling for" the effect modifiers (i.e. always treating them as potential confounders).

**Comment by vsyrgkanis** [comment]
Also I would say that for lineardml using inference=“statsmodels” is preferable (and much less computationally intensive).

**Comment by ncorream** [comment]
Oh! Noted. I would also modify this!

Thank you, I will continue to "play" with my data a bit more and see what can I get from it.

**Comment by vsyrgkanis** [comment]
This issue seems to be addressed.
