### ISSUE TITLE
Treatment effect does not vary depending on treatment value

### ISSUE THREAD

**Issue by drskd** [microsoft/EconML#442]
I would like to have an analysis of sensitivity to the treatment in a pricing context.
I fit the model through the following lines of code.

```
# initiate an EconML cate estimator
est_nonparam = CausalForestDML(model_y=GradientBoostingRegressor(), model_t=GradientBoostingRegressor())
# fit through dowhy
est_nonparam_dw = est_nonparam.dowhy.fit(Y, T, X=X, W=W, Z=Z,
                       instrument_names=instrument_names,
                       outcome_names=["log_demand"],
                       treatment_names=["log_price"], feature_names=confounder_X,
               confounder_names=confounder_W, inference="blb")
```

And estimate the effect for different `log_price` values via the `effect` function as follows:

```
n_estimation = 10
price_range = np.linspace(1.78,1.91,n_estimation)
for i in range(0,n_estimation-1):
    t_pred = est_nonparam_dw.effect(X,T0=price_range[i],T1=price_range[i+1])
```
For each sample, the estimated effect is always the same for all possible treatment values. 
Is it normal? Is this the proper way to perform such an analysis? Would it be because I use the training set in the sensitivity analysis?

Any feedback would gladly be appreciated.

**Comment by vsyrgkanis** [comment]
What do you mean by sensitivity!

it seems you mean how the matginal effect varies with the value of the treatment.

many estimators including the one you are using assume a linear with respect to treatment model. So the marginal effect estimated is constant which is why you are getting the same number.

you could try circumventing this by passing multiple treatments that correspond to some featurization of the origina treatment and rhen taking the derivatives outside of the package.

**Comment by vsyrgkanis** [comment]
See the discussion and extensive response in #378 on how to exactly do that.

seems the same question

**Comment by drskd** [comment]
This is indeed exactly what I was looking for, thanks a lot.
