### ISSUE TITLE
Use case differences between CausalForest versus CausalForestDML

### ISSUE THREAD

**Issue by kfoofw** [microsoft/EconML#444]
Hi there, thank you for the comprehensive package along with the excellent documentation! 

Based on the recent notebook on Generalised Random Forests (https://github.com/microsoft/EconML/blob/master/notebooks/Generalized%20Random%20Forests.ipynb), it seems like `econml` includes both `econml.grf.CausalForest` and `econml.dml.CausalForestDML` (fitting a CausalForest on the residuals of DML).

Is there a difference in the use cases of CATE estimation for a given set of experimental data set between the `CausalForest` vs `CausalForestDML` estimators? Are there situations (or theoretical explanations) that require us to use one over the other?

Thanks a lot once again!

**Comment by vsyrgkanis** [comment]
You should almost always be using causalforestdml.

the causalforest class is more like a helper class so that we can use it as a final model in our cate estimators. 

See also the text at the beginning of the notebook you linked. Let us know if you think there are ways to make this clearer, as indeed the existent of both classes can be confusing.

**Comment by kfoofw** [comment]
Thanks for the fast response!

I understand that the`econml.grf.CausalForest` helper class is used as the final model with the `econml.dml.CausalForestDML` class object, but I'm interested in knowing the advantages of using `CausalForestDML` over `CausalForest` itself especially when both class objects allow for CATE estimation using a set of experimental data using the same workflow of `est.fit(X, T, y)`.

Does this imply that the `CausalForest` helper class object actually obtains a "biased" estimator, and thus inferior in some sense? Or does `CausalForestDML` provide the debiasing, which helps the convergence towards an unbiased estimate of the treatment effects much faster in terms of less data required?

Apologies for the questions, but I really like the whole `econml` package and its documentation on the research theory, so I'm trying to find out the assumptions/advantages on the hybrid combination of DML and CausalForest, especially since CausalForest itself has asymptotic normality properties based on my understanding of the GRF package.

Thanks in advance for any responses!

**Comment by vsyrgkanis** [comment]
The dml residualization helps exactly in removing artifacts of heterogeneous effects that are actually variations in the baseline reward and not variations in the effect and which can occur even in A/B tests due to random imbalances.

The residualization (dml) preprocessing step is also recommended in grf paper in the section on heterogeneous effects. Also it is internally implemented by the grf package as a preprocessing step internally. So cfdml is closer to what you would also get by the R grf package.

Also for some formal theory arguments of how residualization can help in the causal  forest algorithm you can also check our Orthogonal Random Forest paper, which exactly provides a theorem and a setting where residualization plus a causal forest can provably improve performance.

For instance, if you want to control for many more variables W but estimate heterogeneity X only in a small set, then using cfdml can greatly improve performance. Even programmatically cfdml allows you to separate these two variables X and W but cf class only has X

**Comment by kfoofw** [comment]
Thanks @vsyrgkanis for your thorough explanation, and also for your explanation that the `econml.dml.CausalForestDML` class object is closer to the implementation of the R `grf` CausalForest algorithm (due to the dml preprocessing step). 

I'll have to look through the papers to get a better understanding of DML theory.

Thanks once again! :)
