### ISSUE TITLE
can the package work for Python 3.4.5

### ISSUE THREAD

**Issue by victoriasunsun** [microsoft/EconML#528]
hi
this package is very useful but my server only has Python 3.4.5
so whether i can use this package on   Python 3.4.5

**Comment by kbattocchi** [comment]
Python 3.4 has been marked end-of-life since March 18, 2019 (see e.g. https://devguide.python.org/devcycle/#end-of-life-branches), and Python 3.5 has reached end-of-life as well.  Several of the packages that `econml` depends on no longer support those releases, and our package itself also makes use of some features of Python 3.6 (particularly string interpolation), so it is not possible to use it with your version of Python.  I'd highly recommend updating to a supported version of Python since the old versions are no longer receiving security fixes.
