### ISSUE TITLE
DML with CasualForestIV? 

### ISSUE THREAD

**Issue by EgorKraevTransferwise** [microsoft/EconML#548]
Hi! 

this library is truly awesome!

I would like to use CausalForestIV in a similar manner to how CausalForest is used in CausalForestDML, that is I would use eg FLAML to correct for the impact of known confounders, and CausalForestIV to then use instruments and account for effect modifiers. Is that fundamentally a reasonable idea, and if so, how would I best approach it? 
There doesn't seem to be a CausalForestIVDML class, is there a fundamental theoretical reason for that or is it just that no one got around to writing one?

Thanks a lot for your help!

**Comment by vsyrgkanis** [comment]
I would try the ForestDRIV class: see here for usage
https://github.com/microsoft/EconML/blob/deb346803357b090325df6d1cad53f3f699f5763/notebooks/OrthoIV%20and%20DRIV%20Examples.ipynb

what you describe is closer to an OrthoIV estimator with a forest final stage. But due to deprioritization we have not implemented that. Should be easy to implement if you create a child class of orthoiv and replacr tbe _gen_model_final method to generate a IVforest.

however for IV wirh a forest based heterogeneity and in a doubly robust (orthogonal) manner, we already have ForestDRIV which does exactly that.

**Comment by EgorKraevTransferwise** [comment]
Thanks a lot! Will give it a go
