### ISSUE TITLE
[question] multiple treatment variables and model final

### ISSUE THREAD

**Issue by ieriii** [microsoft/EconML#581]
This is more of a question than an issue. Let's say I have the following set up:   
- Y = outcome variable
- T = list of treatment variables [T1, T2, T3]
- X = confounders   

The functional form is:   
- Y = theta_1 * T1 + theta_2 * T2 + theta_3 * T3 + g(X); and
- T1 = m(x) + e
- T2 = m(x) + e
- T3 = m(x) + e
 
I would like to use econML double ML module to do the following:
1. use ML to estimate y_hat = g_hat(X) + u
2. use ML to estimate T1_hat = m_hat(X) + v1
3. use ML to estimate T2_hat = m_hat(X) + v2
4. use ML to estimate T3_hat = m_hat(X) + v3
6. regress the residuals u against v1, v2 and v3 using linear regression.

The intuition of this approach is to (i) net off the confounders X from Y, T1, T2 and T3, (ii) take the residuals and (iii) estimate the impact of the treatment variables on Y.

Is this something that can be implemented with econML? If so, how?   
I have looked at the docs and source code and I think I can do point 1-5 above (correct me if you think I'm wrong) but cannot identify whether point 6 could be possible.
Thank you.

**Comment by kbattocchi** [comment]
Sorry, it isn't clear to me from your question what "point 6" is that you have a question about.  However, what you've outlined is basically how the LinearDML class works; if the thetas do not depend on X then we would call them controls and you should pass them as W, not as X, when calling fit (and pass the three treatments as a single 3-column array as T).  Let us know if there are any additional questions.

**Comment by kbattocchi** [comment]
Yes, that sounds basically right to me - you can print a summary with `summary`, but you can also use `est.intercept_`  for the point estimates, or `est.intercept__inference()` to get an inference object that you can get pvalues, confidence intervals, etc. from, including a dataframe with a summary of all of that information by using `est.intercept__inference().summary_frame()`.

(The coefficients are stored in the intercept because you do not have any X variables, which would generate additional coefficients for each combination of the columns of X and T that would be stored in the `est.coef_` attribute)
