### ISSUE TITLE
DML effect() function returns theta(x)+C instead of theta(x)

### ISSUE THREAD

**Issue by heimengqi** [microsoft/EconML#61]

**Comment by kbattocchi** [comment]
@heimengqi Could you please include a short repro?

**Comment by heimengqi** [comment]
On the final stage of DML, if the final model includes intercept by default, we will fit Y~theta(X)*T+C, then we call predict() will return theta(X)+C instead of theta(X). This problem was found by @vasilismsr in his DMLIV code. I think we will have the similar issue here.

**Comment by kbattocchi** [comment]
@heimengqi By default we set `fit_intercept=False` in the `DMLCateEstimator`'s `model_final`; users should always do that themselves if they use some other model (but I don't see how to enforce that - let me know if you have any suggestions, and we can try to better document this requirement).

In general when filing issues it would be great to include a small code example that has the problem, so that we can directly turn it into a test.

**Comment by heimengqi** [comment]
Okay I see, I forgot the default of final model is fit_intercept=False, then it's not a big deal. Thanks!

**Comment by vsyrgkanis** [comment]
I think we can guard against even people that by mistake use an intercept by simply subtracting the prediction of the final model at T=0. That seems safer to me since its easy to guard aigainst such a mistake

**Comment by kbattocchi** [comment]
@vsyrgkanis That makes sense; I think perhaps we should also warn if `predict(0)` is nonzero (since we can subtract the offset but fitting a model without an offset will give different results).

**Comment by kbattocchi** [comment]
Fixed by #75
