### ISSUE TITLE
Causal graph creation with time series 

### ISSUE THREAD

**Issue by Antoinebattini** [microsoft/EconML#665]
hey everyone, 
First of all, thanks for your incredible work and the access to the library. 
I'm currently working with time-series data, and I had few questions: 
I didn't find anything about creation of causal graph with the analysis of the time series. I have the feeling that the causal graph is more an input than an output. 
Since I'm working with time-series data, I don't know if the treatment effect or calculation of the CATE of a time series on another one is really appropriate since there no "treatment" strictly speaking, because we never have the counterfactual. 

Thanks in advance for the response.

**Comment by kbattocchi** [comment]
For the most part, the causal graphs we work with are implicit (though if you call econml from the dowhy library that's not necessarily true).  Our only estimator that is specifically made for time series data is [DynamicDML](https://econml.azurewebsites.net/spec/estimation/dynamic_dml.html#), but that is tailored to a specific estimation problem which might or might not apply to your situation.  We are interested in expanding to further time series scenarios as we further develop the library.

Could you elaborate on the problem that you're trying to solve?  I'm not sure what you mean about never having the counterfactual - in general many of our estimators run on observational data (rather than, say, randomized trial data), so that might not be a problem, but we do expect there to be a "treatment" whose effect you want to learn.

**Comment by Antoinebattini** [comment]
Thanks for your answers and your help, here is some clarification about my problem.
My first goal is the following one: 
I have features X ( go from 260 to 900) which are times series and the goal is to find the ones whose are causal to an outcome Y which is also a time series. Those are "financial data", so it's possible that some other causal features could been unobserved. 
My first idea was to find the Markov blanket (the theoretical subset of features that are sufficient and causal in the SCM framework). But I didn't find (maybe I missed something) any available code for this with library. 
So my second thought was to take every and each features individually as the "treatment" and evaluate its CATE and select the ones with the higher CATE score.

**Comment by kbattocchi** [comment]
I see.  In general, our library's estimators do assume you already know the causal graph; additionally, if your data is potentially missing other causal factors then you will need some other strong assumptions (like the existence of an instrumental variable) to get unbiased estimates.  If the relationships between the different Xs are completely unrestricted, then it is not necessarily valid to try to compute CATEs (controlling for the other variables) and compare them, because variables could be colliders (downstream of both the treatment and outcome) and controlling for them will give you incorrect results.

There are packages that do causal discovery (trying to infer the graph from data); these necessarily make some additional assumptions in order to learn the dependencies but you could consider running such a tool (e.g. https://github.com/microsoft/causica). However I'm not aware of any such tool that would take the time-series nature of your data into account (and this could make the entire problem far more complicated than it already is - which features can affect which other features, with what sorts of lags?)

**Comment by Antoinebattini** [comment]
Yes I think that the problem is far more complicated than finding causal dependency between variables. 
Thanks for your answers.
