### ISSUE TITLE
Why do SingleTreePolicyInterpreter give different tree output than SingleTreeCateInterpreter?

### ISSUE THREAD

**Issue by titubs** [microsoft/EconML#691]
@kbattocchi Hi Keith,
I was wondering if you can tell me why fundamentally I get totally different tree structures from SingleTreeCateInterpreter VS SingleTreePolicyInterpreter for my model as far as the splits go? Thanks in advance!

**Comment by kbattocchi** [comment]
It's hard to say without more context, but note that the goals of the trees is different: the policy tree should group units which have the same *policy* while the CATE interpreter should group units which have roughly equal treatment effects.  So for instance, if there are two separate groups with positive but quite different treatment effects, then the policy interpreter might group them (because the policy will be to treat both) while the CATE interpreter might keep them separate (because the CATE values are different).

**Comment by titubs** [comment]
@kbattocchi  This is extremely helpful. Thank you so much for breaking this down. Keep up the good work on Causal!
