### ISSUE TITLE
How to treat ATE/CATE of continuous treatment as nonlinear?

### ISSUE THREAD

**Issue by Lllllp93** [microsoft/EconML#714]
Hi I am new to causal inference and EconML, my problem is that how can we treat the ATE/CATE of continous treatment as nonlinear. 

As far as I know, methods like `DML` or `DR` assume the causal effect is linear. For example, `DML` results tell me that  every $1 decrease in price, the sales volume will increase by 100 pieces. Maybe this result is applicable to a certain range(like from $10 to $30) , but of course, we cannot reduce the price without limitation(the effect of $20 to $10 should not be the same as that of $11 to $1 ). So I believe the causal effect of continous treatment should be nonlinear in most cases, but how to figure out this?

One way to do this I think is to build a predictor with treatment and backdoor vars like `P(outcome | treatment,backdoor_vars)`，and then we can compute effect by `P(outcome | treatment=$20,backdoor_vars) - P(outcome | treatment=$10,backdoor_vars)` . But there is not too much causality things and maybe include bias and overfitting.

I would appreciate it if you could kindly help me.

**Comment by kbattocchi** [comment]
You are correct that estimators like DML do assume linearity in the treatment.  One workaround is to augment the treatment vector; for example if you stack the price and the square of the price, then you are fitting a model linear in [p, p**2], which is effectively a quadratic in p.

In our latest public release, we exposed a simple way to achieve this instead of needing to modify the treatment array manually yourself: you can set the `treatment_featurizer` argument to a featurizer that transforms the treatment and the estimator will automatically handle applying the featurizer for you and take it into account when calling methods like `marginal_effect`.  For example, `LinearDML(treatment_featurizer=PolynomialFeatures(degree=2, include_bias=False))` will allow you to fit a model which is quadratic in p instead of linear.

**Comment by Lllllp93** [comment]
> In our latest public release, we exposed a simple way to achieve this instead of needing to modify the treatment array manually yourself: you can set the `treatment_featurizer` argument to a featurizer that transforms the treatment and the estimator will automatically handle applying the featurizer for you and take it into account when calling methods like `marginal_effect`. For example, `LinearDML(treatment_featurizer=PolynomialFeatures(degree=2, include_bias=False))` will allow you to fit a model which is quadratic in p instead of linear.

Many thanks!

**Comment by Lllllp93** [comment]
> In our latest public release, we exposed a simple way to achieve this instead of needing to modify the treatment array manually yourself: you can set the `treatment_featurizer` argument to a featurizer that transforms the treatment and the estimator will automatically handle applying the featurizer for you and take it into account when calling methods like `marginal_effect`. For example, `LinearDML(treatment_featurizer=PolynomialFeatures(degree=2, include_bias=False))` will allow you to fit a model which is quadratic in p instead of linear.

Many thanks!
