### ISSUE TITLE
Couple of questions on the usage of CausalForestDML for HTE

### ISSUE THREAD

**Issue by Anselmmm** [microsoft/EconML#719]
Hi! I've been exploring heterogenous treatment effects (HTE) using this econml (which has been extremely interesting thus far), and have decided to start my experimentation with the CausalForestDML estimator as I was interested in how Causal Trees function all along

So far, I understand that Causal Forests have the ability to provide personalized treatment effects which are heterogenous across different subgroups of the population, and all along the videos I watched on HTE terms this 'effect' as the CATE (or more specifically the Sample Average Treatment effect of each leaf). However, by glancing at the methods available after tuning and fitting the CausalForestDML, it seems that it provides the functionality to compute other types of treatment effects - all of which I'm very confused about and have trouble deriving their meaning and purpose (apart from the conventional few like ATE & ATT).

I therefore would like to clarify the doubts that I currently have (along with some other minor doubts when carrying out experimentations with CausalForestDML):

1. What are the meaning (or rather how are they computed) and purpose of the other effects that are available in the estimator?
     - Constant Marginal ATE
     - Marginal ATE

2. I understand that this has been discussed before in this [post on p values](https://github.com/microsoft/EconML/issues/702), but I'd just like to confirm that if for example `summary()` is called, and if the p-value beside the CATE is reported at 0.003 (assuming a significance level of 5%) - we'd conclude that the CATE is a statistically significant non-zero value?

3. I kind of get how Causal Trees employ the expected MSE as their splitting criterion (`criterion="mse"`). However, I've not encountered the heterogeneity score (`criterion="het"`) before, and don't really understand how it works - would there be any high level explanation of how this metric works, and when we should use it over `mse`? (as my test mse is consistently lower than my training mse which is kind of weird, i.e., 0.0248 vs 0.0323 respectively)

4. Lastly, I'd also like to check if econml provides any form of calibration assessment for evidence of HTE, as provided by Susan Athey's `grf` package in R, and briefly discussed in this [video](https://www.youtube.com/watch?v=fNjToAQ9v3g&list=PLxq_lXOUlvQAoWZEqhRqHNezS30lI49G-&index=11&ab_channel=StanfordGraduateSchoolofBusiness) (14:54 - 16:31) on Causal Forests

I understand that this might be alot of questions to answer, but I'd really greatly appreciate any assistance on this matter as I feel that it will clear up alot of doubts I currently have with regards to Causal Forests within econml, thank you very much!

**Comment by ardiqbal** [comment]
Let me try to answer question 1. I've looked at the source code for quite a while now and found that the DML, either LinearDML or CausalForestDML implements LinearCateEstimator, where from the [docs](https://econml.azurewebsites.net/spec/api.html#api-of-conditional-average-treatment-effect-package): _One particular prevalent assumption is that the outcome 
y
 is linear in the treatment vector and therefore that the marginal effect is constant across treatments_. In other words, _marginal cate = constant marginal cate_. Hence, when you call `model.marginal_effect(T, X)` and give any value of T, you will get the same marginal effect because it is assumed to be constant.

But the real definition of marginal effect from the [docs](https://econml.azurewebsites.net/spec/api.html#api-of-conditional-average-treatment-effect-package), if it not assumed to be constant, is _If treatments are continuous, then one might also be interested in a local effect around a treatment point. The latter translates to estimating a local gradient around a treatment vector conditional on observables_

This picture from Matheus [[here](https://matheusfacure.github.io/python-causality-handbook/22-Debiased-Orthogonal-Machine-Learning.html)](url) helped me to understand that the marginal effect is basically the slope at certain treatment value. The picture shows when the outcome y is not linear to the treatment, thus no linearity assumption that will make the marginal effect to be constant across treatments, but rather change with the treatment.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/17381912/213897902-86d00068-93bf-493e-b7e7-a987fc1f300e.png">

**Comment by Anselmmm** [comment]
Alright, thanks for the clarification!

**Comment by shbyrne** [comment]
Did you ever find a solution to Q.4 in your original post, @soya-beancurd? I've been wondering the same thing.

**Comment by shbyrne** [comment]
@kbattocchi Thanks for clarifying, that sounds great. Looking forward to the release!
