### ISSUE TITLE
Standard errors

### ISSUE THREAD

**Issue by federiconuta** [microsoft/EconML#81]
Dear all,

sorry for rising another issue. 
I cannot see any documentation for computing the standard errors. Is there a way to do it?

I would like to obtain the significance level of the following:
```
est.const_marginal_effect(X_test_first_atc1.T)
```

Thank you all!

**Comment by kbattocchi** [comment]
@federiconuta Sorry, I somehow missed this issue until now.

One possibility with the current release is to use the [bootstrap estimator](https://econml.azurewebsites.net/_autosummary/econml.bootstrap.html#econml.bootstrap.BootstrapEstimator).  However, we're actively working on adding additional ways of doing this and providing a simpler interface, so that in the near future you'll be able to provide an extra `inference` argument to an estimator's `fit` method that will enable inference.

**Comment by federiconuta** [comment]
No problems at all and also many thanks for what you are doing!

So basically I need to create an object "bootstrap estimator" and input the
model estimates?

Il Mer 10 Lug 2019, 15:54 Keith Battocchi <notifications@github.com> ha
scritto:

**Comment by kbattocchi** [comment]
Section 4.4 of our [Double ML notebook](https://github.com/microsoft/EconML/blob/master/notebooks/Double%20Machine%20Learning%20Examples.ipynb) includes an example of how to us the bootstrap estimator which should hopefully make the usage clear, but please let me know if you still have any other questions.

**Comment by federiconuta** [comment]
Perfect. Thank you again!

Il Mer 10 Lug 2019, 16:22 Keith Battocchi <notifications@github.com> ha
scritto:

**Comment by vasilismsr** [comment]
Created #95 in response to this issue.
